// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_MyA1_RYbmQk1wWd0Nxju5UOGMtc95o',
    appId: '1:1048935612570:web:f3e9bdbb3727064cdb9f23',
    messagingSenderId: '1048935612570',
    projectId: 'car-rental-app-v1',
    authDomain: 'car-rental-app-v1.firebaseapp.com',
    storageBucket: 'car-rental-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF76WUPBrVeF7NVEhP8Rl-Suxqgr8g7sk',
    appId: '1:1048935612570:android:ec9fe4a28a83801bdb9f23',
    messagingSenderId: '1048935612570',
    projectId: 'car-rental-app-v1',
    storageBucket: 'car-rental-app-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbYfAGA4H3WO08_mPc_ZtzqglGbpNqkwY',
    appId: '1:1048935612570:ios:e2ac8273435ad2cadb9f23',
    messagingSenderId: '1048935612570',
    projectId: 'car-rental-app-v1',
    storageBucket: 'car-rental-app-v1.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbYfAGA4H3WO08_mPc_ZtzqglGbpNqkwY',
    appId: '1:1048935612570:ios:e2ac8273435ad2cadb9f23',
    messagingSenderId: '1048935612570',
    projectId: 'car-rental-app-v1',
    storageBucket: 'car-rental-app-v1.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0_MyA1_RYbmQk1wWd0Nxju5UOGMtc95o',
    appId: '1:1048935612570:web:66a6438fc7913f26db9f23',
    messagingSenderId: '1048935612570',
    projectId: 'car-rental-app-v1',
    authDomain: 'car-rental-app-v1.firebaseapp.com',
    storageBucket: 'car-rental-app-v1.firebasestorage.app',
  );
}
